# SITE CONFIGURATION
baseurl: ""
url: "https://missionpinball.github.io/"
title: Mission Pinball Hardware
description: "Mission Pinball Hardware"

collections:
  pcbs:
    output: true
    permalink: /pcb/:name.html
  cad_models:
    output: true
    permalink: /cad_models/:name.html

future: true

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "pcbs"
    values:
      layout: pcb
  - scope:
      path: ""
      type: "cad_models"
    values:
      layout: cad_model
